* x264 works again, but need to fine tune further * add avcodec, avutil, swscale, x264 headers and libraries check in configure * new configure options, --with-ffmpeglib --with-ffmpeginc --with--x264lib --withx264inc

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -54,6 +54,15 @@ builtin(include, configure.in.head)
 
 #XXX
 V_STATIC="-static"
+V_LIB_GRABBER=""
+V_INCLUDE_GRABBER=""
+V_OBJ_GRABBER=""
+V_LIB_XIL=""
+V_OBJ_XIL=""
+V_INCLUDE_FFMPEG=""
+V_INCLUDE_X264=""
+V_LIB_FFMPEG=""
+V_LIB_X264=""
 
 AC_ARG_WITH(aix-shm,	--with-aix-shm=path	specify a pathname for the AIX shm X extension library file, lib=$withval, lib="")
 if test "$lib" != "" ; then
@@ -70,6 +79,94 @@ AC_ARG_WITH(qcam,	--with-qcam=dir     specify directory with qcam.h for Connecti
 if test "$qcamdir" != "" -a ! -r $qcamdir/qcam.h ; then
 	echo "'$dir/qcam.h' does not exist"
 	exit 1
+fi
+
+AC_ARG_WITH(ffmpeginc,       --with-ffmpeginc=dir     specify the prefix directory of ffmpeg header, V_INCLUDE_FFMPEG=$withval, V_INCLUDE_FFMPEG="")
+if test "$V_INCLUDE_FFMPEG" != "" ; then
+   if test ! -r $V_INCLUDE_FFMPEG/ffmpeg/avcodec.h ; then
+        echo "Error! you need to have $V_INCLUDE_FFMPEG/ffmpeg/avcodec.h around"
+        exit 1
+   elif test ! -r $V_INCLUDE_FFMPEG/ffmpeg/avutil.h ; then
+        echo "Error! you need to have $V_INCLUDE_FFMPEG/ffmpeg/avutil.h around"
+        exit 1
+   elif test ! -r $V_INCLUDE_FFMPEG/ffmpeg/swscale.h ; then
+        echo "Error! you need to have $V_INCLUDE_FFMPEG/ffmpeg/swscale.h around"
+        exit 1
+   fi
+   echo "checking for FFmpeg headers...yes"
+   V_INCLUDE="$V_INCLUDE -I$V_INCLUDE_FFMPEG"
+
+else
+
+   AC_CHECK_HEADER(ffmpeg/avcodec.h, [], [
+        echo "Error! you need to have avcodec.h around."
+        exit -1
+   ])
+   AC_CHECK_HEADER(ffmpeg/avutil.h, [], [
+        echo "Error! you need to have avutil.h around."
+        exit -1
+   ])
+   AC_CHECK_HEADER(ffmpeg/swscale.h, [], [
+        echo "Error! you need to have swscale.h around."
+        exit -1
+   ])
+fi
+
+AC_ARG_WITH(ffmpeglib,       --with-ffmpeglib=dir     specify the directory of ffmpeg library, V_LIB_FFMPEG=$withval, V_LIB_FFMPEG="")
+if test "$V_LIB_FFMPEG" != "" ; then
+   if test ! -r $V_LIB_FFMPEG/libavcodec.a ; then
+	echo "Error! you need to have $V_LIB_FFMPEG/libavcodec.a around"
+   elif test ! -r $V_LIB_FFMPEG/libavutil.a ; then
+        echo "Error! you need to have $V_LIB_FFMPEG/libavutil.a around"
+   elif test ! -r $V_LIB_FFMPEG/libswscale.a ; then
+        echo "Error! you need to have $V_LIB_FFMPEG/libswscale.a around"
+   fi
+   V_LIB_FFMPEG="-L$V_LIB_FFMPEG -lavcodec -lavutil -lswscale"
+else
+   AC_CHECK_LIB(avcodec, main, [], [
+        echo "Error! you need to have libavcodec around."
+        exit -1
+   ])
+   AC_CHECK_LIB(avutil, main, [], [
+        echo "Error! you need to have libavutil around."
+        exit -1
+   ])
+   AC_CHECK_LIB(swscale, main, [], [
+        echo "Error! you need to have libswscale around."
+        exit -1
+   ])
+   V_LIB_FFMPEG="-lavcodec -lavutil -lswscale"
+fi
+
+AC_ARG_WITH(x264inc,       --with-x264inc=dir     specify the directory of x264 header, V_INCLUDE_X264=$withval, V_INCLUDE_X264="")
+dnl x264 header needs pre-included headers
+dnl
+if test "$V_INCLUDE_X264" != "" ; then
+   if test ! -r $V_INCLUDE_X264/x264.h ; then
+	echo "Error! you need to have $V_INCLUDE_X264/x264.h around."
+	exit 1
+   fi
+   V_INCLUDE="$V_INCLUDE -I$V_INCLUDE_X264"
+elif test ! -r /usr/local/include/x264.h -a ! -r /usr/include/x264.h ; then
+        echo "Error! you need to have x264.h around."
+        exit 1
+else
+   echo "checking for x264.h...yes"
+fi
+
+AC_ARG_WITH(x264lib,       --with-x264lib=dir     specify the directory of x264 library, V_LIB_X264=$withval, V_LIB_X264="")
+if test "$V_LIB_X264" != "" ; then
+   if test ! -r $V_LIB_X264/libx264.a ; then
+        echo "Error! you need to have $V_LIB_X264/libx264.a around"
+	exit 1
+   fi
+   V_LIB_X264="-L$V_LIB_X264 -lx264"
+else
+   AC_CHECK_LIB(x264, main, [], [
+        echo "Error! you need to have libx264 around."
+        exit -1
+   ])
+   V_LIB_X264="-lx264"
 fi
 
 
@@ -145,12 +242,6 @@ fi
 
 # lots of hairy special cases for detecting which frame capture
 # support to compile in
-
-V_LIB_GRABBER=""
-V_INCLUDE_GRABBER=""
-V_OBJ_GRABBER=""
-V_LIB_XIL=""
-V_OBJ_XIL=""
 
 AC_ARG_ENABLE(v4l2old,	--enable-v4l2old    Enable or disable old Video4Linux2 grabber, v4l2old=yes, v4l2old=no)
 if test "$v4l2old" = "yes" ; then
@@ -460,6 +551,8 @@ if test -f codec/encoder-bvc.cpp ; then
 	V_OBJ="$V_OBJ codec/encoder-bvc.o codec/decoder-bvc.o"
 fi
 
+AC_SUBST(V_LIB_FFMPEG)
+AC_SUBST(V_LIB_X264)
 AC_SUBST(V_INCLUDE_GRABBER)
 AC_SUBST(V_LIB_GRABBER)
 AC_SUBST(V_OBJ_GRABBER)
