- Removed Solaris/Linux specific defines from net_udp.c.  Common library is now   clean of UNIX platform specific defines. - Added test for struct addrinfo to IPv6 checks.  Should now work on FreeBSD,   since previous tests excluded it from code it needed. 								-o

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2090,21 +2090,28 @@ if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
 EOF
  
 		echo "$ac_t""yes" 1>&6
-		for ac_hdr in netinet6/in6.h
+else
+  rm -rf conftest*
+  echo "$ac_t""no" 1>&6 
+		echo "configure: warning: IPv6 support not found.  Ignoring request." 1>&2
+fi
+rm -f conftest*
+
+	for ac_hdr in netinet6/in6.h
 do
 ac_safe=`echo "$ac_hdr" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for $ac_hdr""... $ac_c" 1>&6
-echo "configure:2098: checking for $ac_hdr" >&5
+echo "configure:2105: checking for $ac_hdr" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 2103 "configure"
+#line 2110 "configure"
 #include "confdefs.h"
 #include <$ac_hdr>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:2108: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:2115: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -2130,6 +2137,21 @@ else
 fi
 done
 
+	echo $ac_n "checking for struct addrinfo""... $ac_c" 1>&6
+echo "configure:2142: checking for struct addrinfo" >&5
+	cat > conftest.$ac_ext <<EOF
+#line 2144 "configure"
+#include "confdefs.h"
+#include <netdb.h>
+EOF
+if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
+  egrep "addrinfo" >/dev/null 2>&1; then
+  rm -rf conftest*
+  cat >> confdefs.h <<\EOF
+#define HAVE_ST_ADDRINFO 1
+EOF
+
+		echo "$ac_t""yes" 1>&6
 else
   rm -rf conftest*
   echo "$ac_t""no" 1>&6
