Update configure script to better support IPv6 (Suzuki Shinsuke)

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -177,18 +177,136 @@ AC_ARG_ENABLE(debug-mem,
 	fi])
 
 ###############################################################################
-# IPv6 related configuration options
-
+# IPv6 related configuration options (using tcpdump's configure.in)
+AC_MSG_CHECKING([whether to enable IPv6])
 AC_ARG_ENABLE(ipv6,
         [  --enable-ipv6           enable ipv6],
-	AC_DEFINE(HAVE_IPv6))
-
-AC_ARG_ENABLE(kame-ipv6,
-	[  --enable-kame-ipv6      enable kame implementation of ipv6],
-	[
+	[ case "$enableval" in
+	  yes)	AC_MSG_RESULT(yes)
 		AC_DEFINE(HAVE_IPv6)
-		LIBS="$LIBS -L/usr/local/v6/lib -linet6"
+		ipv6=yes
+		;;
+	  *)	AC_MSG_RESULT(no)
+		ipv6=no
+		;;
+	  esac
+	],
+	[ AC_MSG_RESULT(no)
+	  ipv6=no
 	])
+ipv6type=unknown
+ipv6lib=none
+ipv6trylibc=no
+
+# IPv6 Stack Type Detector
+if test "$ipv6" = "yes"; then
+	AC_MSG_CHECKING([ipv6 stack type])
+	for i in inria kame linux-glibc linux-libinet6 toshiba v6d zeta; do
+		case $i in
+		inria)
+			dnl http://www.kame.net/
+			AC_EGREP_CPP(yes, [dnl
+#include <netinet/in.h>
+#ifdef IPV6_INRIA_VERSION
+yes
+#endif],
+				[ipv6type=$i;
+				CFLAGS="-DINET6 $CFLAGS"])
+			;;
+		kame)
+			dnl http://www.kame.net/
+			AC_EGREP_CPP(yes, [dnl
+#include <netinet/in.h>
+#ifdef __KAME__
+yes
+#endif],
+				[ipv6type=$i;
+				ipv6lib=inet6;
+				if test -x /usr/local/v6/lib; then
+					ipv6libdir=/usr/local/v6/lib;
+				else
+					ipv6type=freebsd/netbsd/openbsd
+					ipv6libdir=/usr/lib;
+				fi;
+				ipv6trylibc=yes;
+				CFLAGS="-DINET6 $CFLAGS"])
+			;;
+		linux-glibc)
+			dnl http://www.v6.linux.or.jp/
+			AC_EGREP_CPP(yes, [dnl
+#include <features.h>
+#if defined(__GLIBC__) && __GLIBC__ >= 2 && __GLIBC_MINOR__ >= 1
+yes
+#endif],
+				[ipv6type=$i;
+				CFLAGS="-DINET6 $CFLAGS"])
+			;;
+		linux-libinet6)
+			dnl http://www.v6.linux.or.jp/
+			if test -d /usr/inet6 -o -f /usr/include/netinet/ip6.h; then
+				ipv6type=$i
+				ipv6lib=inet6
+				ipv6libdir=/usr/inet6/lib
+				ipv6trylibc=yes;
+				CFLAGS="-DINET6 -I/usr/inet6/include $CFLAGS"
+			fi
+			;;
+		toshiba)
+			AC_EGREP_CPP(yes, [dnl
+#include <sys/param.h>
+#ifdef _TOSHIBA_INET6
+yes
+#endif],
+				[ipv6type=$i;
+				ipv6lib=inet6;
+				ipv6libdir=/usr/local/v6/lib;
+				CFLAGS="-DINET6 $CFLAGS"])
+			;;
+		v6d)
+			AC_EGREP_CPP(yes, [dnl
+#include </usr/local/v6/include/sys/v6config.h>
+#ifdef __V6D__
+yes
+#endif],
+				[ipv6type=$i;
+				ipv6lib=v6;
+				ipv6libdir=/usr/local/v6/lib;
+				CFLAGS="-I/usr/local/v6/include $CFLAGS"])
+			;;
+		zeta)
+			AC_EGREP_CPP(yes, [dnl
+#include <sys/param.h>
+#ifdef _ZETA_MINAMI_INET6
+yes
+#endif],
+				[ipv6type=$i;
+				ipv6lib=inet6;
+				ipv6libdir=/usr/local/v6/lib;
+				CFLAGS="-DINET6 $CFLAGS"])
+			;;
+		esac
+		if test "$ipv6type" != "unknown"; then
+			break
+		fi
+	done
+	AC_MSG_RESULT($ipv6type)
+fi
+
+if test "$ipv6" = "yes" -a "$ipv6lib" != "none"; then
+	if test -d $ipv6libdir -a -f $ipv6libdir/lib$ipv6lib.a; then
+		LIBS="-L$ipv6libdir -l$ipv6lib $LIBS"
+		echo "You have $ipv6lib library, using it"
+	else
+		if test "$ipv6trylibc" = "yes"; then
+			echo "You do not have $ipv6lib library, using libc"
+		else
+			echo 'Fatal: no $ipv6lib library found.  cannot continue.'
+			echo "You need to fetch lib$ipv6lib.a from appropriate"
+			echo 'ipv6 kit and compile beforehand.'
+			exit 1
+		fi
+	fi
+fi
 
 # Test below are IPv6 specific.  Their result has no bearing if HAVE_IPv6 is
 # not defined.  They are kept outside IPv6 enable check to keep code readable.
@@ -203,8 +321,6 @@ then
 	AC_DEFINE(HAVE_GETIPNODEBYNAME) 
 fi
 
-AC_CHECK_HEADERS(netinet6/in6.h)
-
 AC_CACHE_CHECK(for struct addrinfo in <netdb.h>, ucl_cv_st_addrinfo_in_netdb_h,
 	AC_EGREP_HEADER(addrinfo,
 		netdb.h,
@@ -217,11 +333,7 @@ fi
 
 AC_CACHE_CHECK(for sin6_len in struct sockaddr_in6, ucl_cv_sin6_len,
 	[AC_TRY_COMPILE([
-		#ifdef HAVE_NETINET6_IN6_H
-		#include <netinet6/in6.h>
-		#else
 		#include <netinet/in.h>
-		#endif /* HAVE_NETINET_IN6_H */
 	],[
 		struct sockaddr_in6	s_in;
 		s_in.sin6_len = 0;
