regenerated configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4500,7 +4500,10 @@ echo "$as_me: error: ${with_tclconfig} directory doesn't contain tclConfig.sh" >
 			`ls -d /usr/contrib/lib 2>/dev/null` \
 			`ls -d /usr/lib64 2>/dev/null` \
 			`ls -d /usr/lib 2>/dev/null` \
+			`ls -d /usr/lib64/tcl[8-9].[0-9]* 2>/dev/null` \
 			`ls -d /usr/lib/tcl[8-9].[0-9]* 2>/dev/null` \
+			`ls -d /usr/local/lib64/tcl[8-9].[0-9]* 2>/dev/null` \
+			`ls -d /usr/local/lib/tcl[8-9].[0-9]* 2>/dev/null` \
 			; do
 		    if test -f "$i/tclConfig.sh" ; then
 			ac_cv_c_tclconfig=`(cd $i; pwd)`
@@ -4725,7 +4728,10 @@ echo "$as_me: error: ${with_tkconfig} directory doesn't contain tkConfig.sh" >&2
 			`ls -d /usr/contrib/lib 2>/dev/null` \
 			`ls -d /usr/lib64 2>/dev/null` \
 			`ls -d /usr/lib 2>/dev/null` \
+			`ls -d /usr/lib64/tk[8-9].[0-9]* 2>/dev/null` \
 			`ls -d /usr/lib/tk[8-9].[0-9]* 2>/dev/null` \
+			`ls -d /usr/local/lib64/tk[8-9].[0-9]* 2>/dev/null` \
+			`ls -d /usr/local/lib/tk[8-9].[0-9]* 2>/dev/null` \
 			; do
 		    if test -f "$i/tkConfig.sh" ; then
 			ac_cv_c_tkconfig=`(cd $i; pwd)`
@@ -6717,6 +6723,137 @@ echo "${ECHO_T}$ac_cv_header_linux_videodev_h" >&6; }
 fi
 if test $ac_cv_header_linux_videodev_h = yes; then
    have_videodev_h=yes;
+else
+  if test "${ac_cv_header__usr_local_include_linux_videodev_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for /usr/local/include/linux/videodev.h" >&5
+echo $ECHO_N "checking for /usr/local/include/linux/videodev.h... $ECHO_C" >&6; }
+if test "${ac_cv_header__usr_local_include_linux_videodev_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header__usr_local_include_linux_videodev_h" >&5
+echo "${ECHO_T}$ac_cv_header__usr_local_include_linux_videodev_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking /usr/local/include/linux/videodev.h usability" >&5
+echo $ECHO_N "checking /usr/local/include/linux/videodev.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include </usr/local/include/linux/videodev.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking /usr/local/include/linux/videodev.h presence" >&5
+echo $ECHO_N "checking /usr/local/include/linux/videodev.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include </usr/local/include/linux/videodev.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: /usr/local/include/linux/videodev.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: /usr/local/include/linux/videodev.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /usr/local/include/linux/videodev.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: /usr/local/include/linux/videodev.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: /usr/local/include/linux/videodev.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: /usr/local/include/linux/videodev.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /usr/local/include/linux/videodev.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: /usr/local/include/linux/videodev.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /usr/local/include/linux/videodev.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: /usr/local/include/linux/videodev.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /usr/local/include/linux/videodev.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: /usr/local/include/linux/videodev.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /usr/local/include/linux/videodev.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: /usr/local/include/linux/videodev.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: /usr/local/include/linux/videodev.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: /usr/local/include/linux/videodev.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for /usr/local/include/linux/videodev.h" >&5
+echo $ECHO_N "checking for /usr/local/include/linux/videodev.h... $ECHO_C" >&6; }
+if test "${ac_cv_header__usr_local_include_linux_videodev_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header__usr_local_include_linux_videodev_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header__usr_local_include_linux_videodev_h" >&5
+echo "${ECHO_T}$ac_cv_header__usr_local_include_linux_videodev_h" >&6; }
+
+fi
+if test $ac_cv_header__usr_local_include_linux_videodev_h = yes; then
+   have_videodev_h=yes;
+fi
+
+
 fi
 
 
@@ -7273,11 +7410,11 @@ echo "${ECHO_T}$ac_cv_header_libv4lconvert_h" >&6; }
 
 fi
 if test $ac_cv_header_libv4lconvert_h = yes; then
-   have_videodev_h=yes;
+   have_libv4lconvert_h=yes;
 fi
 
 
-if test x$have_videodev_h = xyes; then
+if test x$have_libv4lconvert_h = xyes; then
         V_DEFINE="$V_DEFINE -DHAVE_LIBV4L"
         if test x$have_V4L = xyes; then
                 V_LIB_GRABBER="$V_LIB_GRABBER -lv4l1"
@@ -7512,8 +7649,10 @@ sparc-sun-sunos*)
 	V_LIB="$V_LIB -lipc"
 	;;
 *-*-netbsd*)
+	V_DEFINE="$V_DEFINE -DNetBSD"
 	V_STATIC=""
 	V_TARCMD="tar -h -c -f"
+	OPSYS=netbsd
 	;;
 *-*-freebsd*)
 	V_STATIC=""
