Updates for configure - mostly for Snow Leopard build, but also some general reshuffling and tidy up.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -29,9 +29,7 @@ case "$arch" in
     case "$target" in (*darwin*) V_DEFINE="$V_DEFINE -DSYS_DARWIN";; esac
     ppc_conf="--disable-altivec"
     ppc_tune="-mcpu=G3"
-    echo test1
     if sysctl hw.vectorunit 2>/dev/null | grep "hw.vectorunit: 1" >/dev/null 2>&1; then
-    echo testa
     	ppc_conf=""
     	ppc_tune="-mcpu=G4 -mtune=G4"
     fi
@@ -53,6 +51,22 @@ V_OBJ_XIL=""
 V_LIB_FFMPEG=""
 V_LIB_X264=""
 
+dnl Optimisation in H261 decoder needs to be turned off for GCC 2.96 
+
+AC_MSG_CHECKING([for buggy version of GCC-2.96])
+if test $CC = gcc ; then
+     if $CC --version | grep 2.96 >&/dev/null; then
+           AC_MSG_RESULT([Yes - Turning off optimisation for dct code])
+           V_CCOPT_H261="";
+     else
+           AC_MSG_RESULT(no)
+     fi
+fi
+
+if test -f codec/encoder-bvc.cpp ; then
+	V_OBJ="$V_OBJ codec/encoder-bvc.o codec/decoder-bvc.o"
+fi
+
 AC_ARG_WITH(aix-shm,	--with-aix-shm=path	specify a pathname for the AIX shm X extension library file, lib=$withval, lib="")
 if test "$lib" != "" ; then
 	if test ! -r $lib ; then
@@ -70,171 +84,6 @@ if test "$qcamdir" != "" -a ! -r $qcamdir/qcam.h ; then
 	exit 1
 fi
 
-AC_ARG_ENABLE(gpl,	--enable-gpl	Enable or disable  use of gpl functionality - H264 MPEG4 Swscale, gpl="yes", gpl="no")
-if test "$gpl" = "yes" ; then
-  V_DEFINE="$V_DEFINE -DHAVE_SWSCALE"
-  V_OBJ="$V_OBJ codec/packetbuffer.o codec/databuffer.o \
-    codec/ffmpeg_codec.o codec/encoder-mpeg4.o codec/decoder-mpeg4.o \
-    codec/x264encoder.o codec/encoder-h264.o codec/decoder-h264.o \
-    codec/rtp_h264_depayloader.o render/color-swscale.o video/deinterlace.o"
-else
-  V_OBJ="$V_OBJ render/color-true.o  render/color-hi.o"
-fi
-
-AC_CHECK_PROG(DOWNLOAD, wget, [wget -O -])
-AC_CHECK_PROG(DOWNLOAD, curl, [curl -s])
-
-AC_ARG_WITH(ffmpegver,       --with-ffmpegver=ffmpeg-version     specify the version of ffmpeg to download and build, ffmpegver=$withval, ffmpegver=ffmpeg-0.5)
-AC_ARG_ENABLE(ffmpeg-co,	--disable-ffmpeg-co	Enable or disable ffmpeg download, ffmpegco="no", ffmpegco="yes")
-if test "$ffmpegco" = "yes" ; then
-  if test "$gpl" = "yes" ; then
-   if test ! -r ${ffmpegver} ; then
-     echo "Downloading ${ffmpegver} from www.ffmpeg.org ..."
-     ${DOWNLOAD} http://www.ffmpeg.org/releases/${ffmpegver}.tar.bz2 | tar xjf - && rm -r ffmpeg ; ln -s ${ffmpegver} ffmpeg
-   fi
-   echo "Configuring ffmpeg..."
-   cd ffmpeg; ./configure --prefix=$V_PATH/ffmpeg $ppc_conf --enable-gpl --enable-swscale --enable-postproc; cd ..
-   V_INCLUDE="$V_INCLUDE -Iffmpeg/include -Iffmpeg"
-   V_CODEC_LIB="$V_CODEC_LIB ffmpeg/lib/libavcodec.a ffmpeg/lib/libavutil.a ffmpeg/lib/libswscale.a ffmpeg/lib/libpostproc.a"
-  else 
-    echo "ffmpeg not available without --enable-gpl"
-  fi
-fi
-
-AC_ARG_WITH(x264ver,       --with-x264ver=x264ver-version     specify the version of x264 to download and build, x264ver=$withval, x264ver=x264-snapshot-20070413-2245)
-AC_ARG_ENABLE(x264-co,        --disable-x264-co      Enable or disable x264 download, x264co="no", x264co="yes")
-if test "$x264co" = "yes" ; then
-  if test "$gpl" = "yes" ; then
-   if test ! -r ${x264ver} ; then
-     echo "Downloading ${x264ver} (r650) of x264 from videolan.org ..."
-     #svn checkout -r 650 svn://svn.videolan.org/x264/trunk x264
-     ${DOWNLOAD} http://downloads.videolan.org/pub/videolan/x264/snapshots/${x264ver}.tar.bz2 | tar xjf - && ln -sf ${x264ver} x264
-   fi
-   echo "Configuring x264..."
-   cd x264; ./configure --prefix=$V_PATH/x264; cd ..
-   V_INCLUDE="$V_INCLUDE -Ix264/include"
-   V_CODEC_LIB="$V_CODEC_LIB x264/lib/libx264.a"
-  else 
-    echo "x264 not available without --enable-gpl"
-  fi
-fi
-
-AC_ARG_WITH(ffmpeginc,       --with-ffmpeginc=dir     specify the prefix directory of ffmpeg header, ffmpeginc=$withval, ffmpeginc="")
-AC_ARG_WITH(ffmpeglib,       --with-ffmpeglib=dir     specify the directory of ffmpeg library, ffmpeglib=$withval, ffmpeglib="")
-
-if test "$gpl" = "yes" ; then
-  if test "$ffmpegco" != "yes"; then
-
-	if test "$ffmpeginc" != "" ; then
-	   if test ! -r $ffmpeginc/ffmpeg/avcodec.h ; then
-	        echo "Error! you need to have $ffmpeginc/ffmpeg/avcodec.h around"
-	        exit 1
-	   elif test ! -r $ffmpeginc/ffmpeg/avutil.h ; then
-	        echo "Error! you need to have $ffmpeginc/ffmpeg/avutil.h around"
-	        exit 1
-	   elif test ! -r $ffmpeginc/ffmpeg/swscale.h ; then
-	        echo "Error! you need to have $ffmpeginc/ffmpeg/swscale.h around"
-	        exit 1
-	   fi
-	   echo "checking for FFmpeg headers...yes"
-	   V_INCLUDE="$V_INCLUDE -I$ffmpeginc"
-	
-	else
-
-	   AC_CHECK_HEADER(ffmpeg/avcodec.h, [], [
-        	echo "Error! you need to have avcodec.h around."
-	        exit -1
-	   ])
-	   AC_CHECK_HEADER(ffmpeg/avutil.h, [], [
-	        echo "Error! you need to have avutil.h around."
-	        exit -1
-	   ])
-	   AC_CHECK_HEADER(ffmpeg/swscale.h, [], [
-	        echo "Error! you need to have swscale.h around."
-	        exit -1
-	   ])
-	fi
-
-	if test "$ffmpeglib" != "" ; then
-	   if test ! -r $ffmpeglib/libavcodec.a ; then
-		echo "Error! you need to have $ffmpeglib/libavcodec.a around"
-	   elif test ! -r $ffmpeglib/libavutil.a ; then
-	        echo "Error! you need to have $ffmpeglib/libavutil.a around"
-	   elif test ! -r $ffmpeglib/libswscale.a ; then
-	        echo "Error! you need to have $ffmpeglib/libswscale.a around"
-           elif test ! -r $ffmpeglib/libpostproc.a ; then
-                echo "Error! you need to have $ffmpeglib/libpostproc.a around"
-           fi
-	   
-	   V_LIB_FFMPEG="-L$ffmpeglib -lavcodec -lavutil -lswscale -lpostproc"
-	else
-	   AC_CHECK_LIB(avcodec, main, [], [
-	        echo "Error! you need to have libavcodec around."
-	        exit -1
-	   ])
-	   AC_CHECK_LIB(avutil, main, [], [
-	        echo "Error! you need to have libavutil around."
-	        exit -1
-	   ])
-	   AC_CHECK_LIB(swscale, main, [], [
-	        echo "Error! you need to have libswscale around."
-	        exit -1
-	   ])
-
-           AC_CHECK_LIB(postproc, main, [], [
-                echo "Error! you need to have libpostproc around."
-                exit -1
-           ])
-
-	   V_LIB_FFMPEG="-lavcodec -lavutil -lswscale -lpostproc"
-	fi
-  fi 
-fi
-
-AC_ARG_WITH(x264inc,       --with-x264inc=dir     specify the directory of x264 header, x264inc=$withval, x264inc="")
-AC_ARG_WITH(x264lib,       --with-x264lib=dir     specify the directory of x264 library, x264lib=$withval, x264lib="")
-if test "$gpl" = "yes" ; then
-  if test "$x264co" != "yes" ; then
-	if test "$x264inc" != "" ; then
-	   if test ! -r $x264inc/x264.h ; then
-	        echo "Error! you need to have $x264inc/x264.h around."
-	        exit 1
-	   fi
-	   V_INCLUDE="$V_INCLUDE -I$x264inc"
-	elif test ! -r /usr/local/include/x264.h -a ! -r /usr/include/x264.h ; then
-	        echo "Error! you need to have x264.h around."
-	        exit 1
-	else
-	   echo "checking for x264.h...yes"
-	fi
-
-	if test "$x264lib" != "" ; then
-	   if test ! -r $x264lib/libx264.a ; then
-	        echo "Error! you need to have $x264lib/libx264.a around"
-		exit 1
-	   fi
-	   V_LIB_X264="-L$x264lib -lx264"
-	else
-	   AC_CHECK_LIB(x264, main, [], [
-	        echo "Error! you need to have libx264 around."
-	        exit -1
-	   ])
-	   V_LIB_X264="-lx264"
-	fi
- fi
-fi
-
-V_CPUDETECT=""
-AC_ARG_ENABLE(cpudetect, --disable-cpudetect     Enable or disable runtime cpu detection, cpudetect="no", cpudetect="yes")
-if test "$gpl" = "yes" ; then
- if test "$cpudetect" = "yes"; then
-    echo "using CPU runtime detection..."
-    V_CPUDETECT="-DRUNTIME_CPUDETECT"
-    V_CPUDETECT_OBJ="cpu/cpudetect.o cpu/cpuid.o"
- fi
- else 
-   echo "No runtime cputect without --enable-gpl"
-fi
 
 V_DV=""
 dnl dv decoding support
@@ -687,15 +536,21 @@ armv4l-*-linux)
         if test "$target_cpu" = powerpc; then
             V_CCOPT="-O2 $ppc_tune"
         fi
-	if ! file -L  /System/Library/Frameworks//QuickTime.framework/QuickTime 2>/dev/null | grep x86_64 >/dev/null 2>&1; then
-          V_CCOPT="$V_CCOPT -arch i386"
+dnl Check for 64-bit host gcc - in Snow Leopard+
+        AC_MSG_CHECKING([for 64-bit gcc on OSX])
+	if gcc -v 2>&1 | grep host=x86_64 >& /dev/null ; then
+dnl Check for lack of 64-bit support in QT - an issue in Snow Leopard+
+	   if ! file -L  /System/Library/Frameworks/QuickTime.framework/QuickTime 2>&1 | grep x86_64 >&/dev/null; then
+              AC_MSG_RESULT([Yes but forcing 32-bit due to QT])
+              V_CCOPT="$V_CCOPT -arch i386"
+              V_LDFLAGS="$V_LDFLAGS -arch i386  -mmacosx-version-min=10.4"
+dnl If gcc 32bit then we need to set these flags for compilation of ffmpeg and x264
+              V_CCLDFLAGS32="LDFLAGS='-arch i386 -mmacosx-version-min=10.4' CFLAGS='-arch i386'"
+	   fi
+	else
+              AC_MSG_RESULT([No - using 32-bit])
 	fi
         OPSYS=macosx
-        ;;
-esac
-
-case "$target" in
-   *-*-darwin*)
         V_OBJ_GRABBER="$V_OBJ_GRABBER video/grabber-macosx.o video/yuv_convert.o"
         ;;
    *)
@@ -703,20 +558,178 @@ case "$target" in
         ;;
 esac
 
-dnl Optimisation in H261 decoder needs to be turned off for GCC 2.96 
-
-if test $CC = gcc ; then
-     echo $ac_n "checking version of GCC""... $ac_c"
-     GCC_version=`$CC --version`
-     echo "$GCC_version"
-     if test "$GCC_version" = 2.96 ; then
-           echo "Turning off optimisation for dct code"
-           V_CCOPT_H261="";
-     fi
+AC_ARG_ENABLE(gpl,	--enable-gpl	Enable or disable  use of gpl functionality - H264 MPEG4 Swscale, gpl="yes", gpl="no")
+if test "$gpl" = "yes" ; then
+  V_DEFINE="$V_DEFINE -DHAVE_SWSCALE"
+  V_OBJ="$V_OBJ codec/packetbuffer.o codec/databuffer.o \
+    codec/ffmpeg_codec.o codec/encoder-mpeg4.o codec/decoder-mpeg4.o \
+    codec/x264encoder.o codec/encoder-h264.o codec/decoder-h264.o \
+    codec/rtp_h264_depayloader.o render/color-swscale.o video/deinterlace.o"
+else
+  V_OBJ="$V_OBJ render/color-true.o  render/color-hi.o"
 fi
 
-if test -f codec/encoder-bvc.cpp ; then
-	V_OBJ="$V_OBJ codec/encoder-bvc.o codec/decoder-bvc.o"
+AC_CHECK_PROG(DOWNLOAD, wget, [wget -O -])
+AC_CHECK_PROG(DOWNLOAD, curl, [curl -s])
+
+AC_ARG_WITH(ffmpegver,       --with-ffmpegver=ffmpeg-version     specify the version of ffmpeg to download and build, ffmpegver=$withval, ffmpegver=ffmpeg)
+AC_ARG_ENABLE(ffmpeg-co,	--disable-ffmpeg-co	Enable or disable ffmpeg download, ffmpegco="no", ffmpegco="yes")
+if test "$ffmpegco" = "yes" ; then
+  if test "$gpl" = "yes" ; then
+   if test ! -d ${ffmpegver} ; then
+      echo "Checking out r20462 (and 29824 of libswscale) of ffmpeg from svn://svn.ffmpeg.org/ffmpeg/trunk..."
+      svn checkout -q -r 20462 svn://svn.ffmpeg.org/ffmpeg/trunk ffmpeg
+      svn checkout -q -r 29824 svn://svn.ffmpeg.org/mplayer/trunk/libswscale  ffmpeg/libswscale
+   fi
+   patch --dry-run -sf -p0 < ffmpeg.iocom.patch >& /dev/null
+   if test $? = 0; then
+      echo "Patching ffmpeg h264 for IOCOM decode compatibility..."
+      patch -p0 < ffmpeg.iocom.patch
+   else
+      echo "ffmpeg has already been patched for IOCOM decode compatibility"
+   fi
+   echo "Configuring ffmpeg..."
+   echo "cd ffmpeg && ${V_CCLDFLAGS32} ./configure --prefix=$V_PATH/ffmpeg $ppc_conf --enable-gpl --enable-postproc; cd .."
+   cd ffmpeg && eval ${V_CCLDFLAGS32} ./configure --prefix=$V_PATH/ffmpeg $ppc_conf --enable-gpl --enable-postproc; cd ..
+   V_INCLUDE="$V_INCLUDE -Iffmpeg/include -Iffmpeg"
+   V_CODEC_LIB="$V_CODEC_LIB -Lffmpeg/lib -lavcodec -lavutil -lswscale -lpostproc "
+  else 
+   echo "ffmpeg not available without --enable-gpl"
+  fi
+fi
+
+AC_ARG_WITH(x264ver,       --with-x264ver=x264ver-version     specify the version of x264 to download and build, x264ver=$withval, x264ver=x264-snapshot-20090708-2245)
+AC_ARG_ENABLE(x264-co,        --disable-x264-co      Enable or disable x264 download, x264co="no", x264co="yes")
+if test "$x264co" = "yes" ; then
+  if test "$gpl" = "yes" ; then
+   if test ! -d ${x264ver} ; then
+     echo "Downloading ${x264ver} of x264 from videolan.org ..."
+     ${DOWNLOAD} http://downloads.videolan.org/pub/videolan/x264/snapshots/${x264ver}.tar.bz2 | tar xjf - && ln -sf ${x264ver} x264
+   fi
+   echo "Configuring x264..."
+   cd x264 && eval ${V_CCLDFLAGS32} ./configure --prefix=$V_PATH/x264; cd ..
+   V_INCLUDE="$V_INCLUDE -Ix264/include"
+   V_CODEC_LIB="$V_CODEC_LIB -Lx264/lib -lx264"
+  else 
+   echo "x264 not available without --enable-gpl"
+  fi
+fi
+
+AC_ARG_WITH(ffmpeginc,       --with-ffmpeginc=dir     specify the prefix directory of ffmpeg header, ffmpeginc=$withval, ffmpeginc="")
+AC_ARG_WITH(ffmpeglib,       --with-ffmpeglib=dir     specify the directory of ffmpeg library, ffmpeglib=$withval, ffmpeglib="")
+
+if test "$gpl" = "yes" ; then
+  if test "$ffmpegco" != "yes"; then
+
+	if test "$ffmpeginc" != "" ; then
+	   if test ! -r $ffmpeginc/ffmpeg/avcodec.h ; then
+	        echo "Error! you need to have $ffmpeginc/ffmpeg/avcodec.h around"
+	        exit 1
+	   elif test ! -r $ffmpeginc/ffmpeg/avutil.h ; then
+	        echo "Error! you need to have $ffmpeginc/ffmpeg/avutil.h around"
+	        exit 1
+	   elif test ! -r $ffmpeginc/ffmpeg/swscale.h ; then
+	        echo "Error! you need to have $ffmpeginc/ffmpeg/swscale.h around"
+	        exit 1
+	   fi
+	   echo "checking for FFmpeg headers...yes"
+	   V_INCLUDE="$V_INCLUDE -I$ffmpeginc"
+	
+	else
+
+	   AC_CHECK_HEADER(ffmpeg/avcodec.h, [], [
+        	echo "Error! you need to have avcodec.h around."
+	        exit -1
+	   ])
+	   AC_CHECK_HEADER(ffmpeg/avutil.h, [], [
+	        echo "Error! you need to have avutil.h around."
+	        exit -1
+	   ])
+	   AC_CHECK_HEADER(ffmpeg/swscale.h, [], [
+	        echo "Error! you need to have swscale.h around."
+	        exit -1
+	   ])
+	fi
+
+	if test "$ffmpeglib" != "" ; then
+	   if test ! -r $ffmpeglib/libavcodec.a ; then
+		echo "Error! you need to have $ffmpeglib/libavcodec.a around"
+	   elif test ! -r $ffmpeglib/libavutil.a ; then
+	        echo "Error! you need to have $ffmpeglib/libavutil.a around"
+	   elif test ! -r $ffmpeglib/libswscale.a ; then
+	        echo "Error! you need to have $ffmpeglib/libswscale.a around"
+           elif test ! -r $ffmpeglib/libpostproc.a ; then
+                echo "Error! you need to have $ffmpeglib/libpostproc.a around"
+           fi
+	   
+	   V_LIB_FFMPEG="-L$ffmpeglib -lavcodec -lavutil -lswscale -lpostproc"
+	else
+	   AC_CHECK_LIB(avcodec, main, [], [
+	        echo "Error! you need to have libavcodec around."
+	        exit -1
+	   ])
+	   AC_CHECK_LIB(avutil, main, [], [
+	        echo "Error! you need to have libavutil around."
+	        exit -1
+	   ])
+	   AC_CHECK_LIB(swscale, main, [], [
+	        echo "Error! you need to have libswscale around."
+	        exit -1
+	   ])
+
+           AC_CHECK_LIB(postproc, main, [], [
+                echo "Error! you need to have libpostproc around."
+                exit -1
+           ])
+
+	   V_LIB_FFMPEG="-lavcodec -lavutil -lswscale -lpostproc"
+	fi
+  fi 
+fi
+
+AC_ARG_WITH(x264inc,       --with-x264inc=dir     specify the directory of x264 header, x264inc=$withval, x264inc="")
+AC_ARG_WITH(x264lib,       --with-x264lib=dir     specify the directory of x264 library, x264lib=$withval, x264lib="")
+if test "$gpl" = "yes" ; then
+  if test "$x264co" != "yes" ; then
+	if test "$x264inc" != "" ; then
+	   if test ! -r $x264inc/x264.h ; then
+	        echo "Error! you need to have $x264inc/x264.h around."
+	        exit 1
+	   fi
+	   V_INCLUDE="$V_INCLUDE -I$x264inc"
+	elif test ! -r /usr/local/include/x264.h -a ! -r /usr/include/x264.h ; then
+	        echo "Error! you need to have x264.h around."
+	        exit 1
+	else
+	   echo "checking for x264.h...yes"
+	fi
+
+	if test "$x264lib" != "" ; then
+	   if test ! -r $x264lib/libx264.a ; then
+	        echo "Error! you need to have $x264lib/libx264.a around"
+		exit 1
+	   fi
+	   V_LIB_X264="-L$x264lib -lx264"
+	else
+	   AC_CHECK_LIB(x264, main, [], [
+	        echo "Error! you need to have libx264 around."
+	        exit -1
+	   ])
+	   V_LIB_X264="-lx264"
+	fi
+ fi
+fi
+
+V_CPUDETECT=""
+AC_ARG_ENABLE(cpudetect, --disable-cpudetect     Enable or disable runtime cpu detection, cpudetect="no", cpudetect="yes")
+if test "$gpl" = "yes" ; then
+ if test "$cpudetect" = "yes"; then
+    echo "Using CPU runtime detection..."
+    V_CPUDETECT="-DRUNTIME_CPUDETECT"
+    V_CPUDETECT_OBJ="cpu/cpudetect.o cpu/cpuid.o"
+ fi
+ else 
+   echo "No runtime cputect without --enable-gpl"
 fi
 
 AC_SUBST(V_LIB_FFMPEG)
