add ffmpeg,x264 checkout

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -6,9 +6,10 @@ AC_INIT(main.cpp)
 V_PROG="vic"
 V_ALL="$V_PROG"
 V_SHM="-DUSE_SHM"
-
+V_PATH=`pwd`
 V_OBJ=""
 V_LIB=""
+V_CODEC_LIB=""
 
 #ARCH DETECTION
 arch=`uname -m`
@@ -59,8 +60,6 @@ V_INCLUDE_GRABBER=""
 V_OBJ_GRABBER=""
 V_LIB_XIL=""
 V_OBJ_XIL=""
-V_INCLUDE_FFMPEG=""
-V_INCLUDE_X264=""
 V_LIB_FFMPEG=""
 V_LIB_X264=""
 
@@ -81,99 +80,123 @@ if test "$qcamdir" != "" -a ! -r $qcamdir/qcam.h ; then
 	exit 1
 fi
 
-AC_ARG_WITH(ffmpeginc,       --with-ffmpeginc=dir     specify the prefix directory of ffmpeg header, V_INCLUDE_FFMPEG=$withval, V_INCLUDE_FFMPEG="")
-if test "$V_INCLUDE_FFMPEG" != "" ; then
-   if test ! -r $V_INCLUDE_FFMPEG/ffmpeg/avcodec.h ; then
-        echo "Error! you need to have $V_INCLUDE_FFMPEG/ffmpeg/avcodec.h around"
-        exit 1
-   elif test ! -r $V_INCLUDE_FFMPEG/ffmpeg/avutil.h ; then
-        echo "Error! you need to have $V_INCLUDE_FFMPEG/ffmpeg/avutil.h around"
-        exit 1
-   elif test ! -r $V_INCLUDE_FFMPEG/ffmpeg/swscale.h ; then
-        echo "Error! you need to have $V_INCLUDE_FFMPEG/ffmpeg/swscale.h around"
-        exit 1
-   fi
-   echo "checking for FFmpeg headers...yes"
-   V_INCLUDE="$V_INCLUDE -I$V_INCLUDE_FFMPEG"
-
-else
-
-   AC_CHECK_HEADER(ffmpeg/avcodec.h, [], [
-        echo "Error! you need to have avcodec.h around."
-        exit -1
-   ])
-   AC_CHECK_HEADER(ffmpeg/avutil.h, [], [
-        echo "Error! you need to have avutil.h around."
-        exit -1
-   ])
-   AC_CHECK_HEADER(ffmpeg/swscale.h, [], [
-        echo "Error! you need to have swscale.h around."
-        exit -1
-   ])
+AC_ARG_ENABLE(ffmpeg-co,	--disable-ffmpeg-co	Enable or disable ffmpeg svn checkout, ffmpegco="no", ffmpegco="yes")
+if test "$ffmpegco" = "yes" ; then
+   echo "checking out ffmpeg from  svn://svn.mplayerhq.hu/ffmpeg/trunk..."
+   svn checkout svn://svn.mplayerhq.hu/ffmpeg/trunk ffmpeg
+   echo "Configuring ffmpeg..."
+   cd ffmpeg; ./configure --prefix=$V_PATH/ffmpeg --enable-gpl --enable-swscaler; cd ..
+   V_INCLUDE="$V_INCLUDE -Iffmpeg/include"
+   V_CODEC_LIB="$V_CODEC_LIB ffmpeg/lib/libavcodec.a ffmpeg/lib/libavutil.a ffmpeg/lib/libswscale.a"
 fi
 
-AC_ARG_WITH(ffmpeglib,       --with-ffmpeglib=dir     specify the directory of ffmpeg library, V_LIB_FFMPEG=$withval, V_LIB_FFMPEG="")
-if test "$V_LIB_FFMPEG" != "" ; then
-   if test ! -r $V_LIB_FFMPEG/libavcodec.a ; then
-	echo "Error! you need to have $V_LIB_FFMPEG/libavcodec.a around"
-   elif test ! -r $V_LIB_FFMPEG/libavutil.a ; then
-        echo "Error! you need to have $V_LIB_FFMPEG/libavutil.a around"
-   elif test ! -r $V_LIB_FFMPEG/libswscale.a ; then
-        echo "Error! you need to have $V_LIB_FFMPEG/libswscale.a around"
-   fi
-   V_LIB_FFMPEG="-L$V_LIB_FFMPEG -lavcodec -lavutil -lswscale"
-else
-   AC_CHECK_LIB(avcodec, main, [], [
-        echo "Error! you need to have libavcodec around."
-        exit -1
-   ])
-   AC_CHECK_LIB(avutil, main, [], [
-        echo "Error! you need to have libavutil around."
-        exit -1
-   ])
-   AC_CHECK_LIB(swscale, main, [], [
-        echo "Error! you need to have libswscale around."
-        exit -1
-   ])
-   V_LIB_FFMPEG="-lavcodec -lavutil -lswscale"
+AC_ARG_ENABLE(x264-co,        --disable-x264-co      Enable or disable x264 svn checkout, x264co="no", x264co="yes")
+if test "$x264co" = "yes" ; then
+   echo "checking out x264 from  svn co svn://svn.videolan.org/x264/trunk..."
+   svn checkout svn://svn.videolan.org/x264/trunk x264
+   echo "Configuring x264..."
+   cd x264; ./configure --prefix=$V_PATH/x264; cd ..
+   V_INCLUDE="$V_INCLUDE -Ix264/include"
+   V_CODEC_LIB="$V_CODEC_LIB x264/lib/libx264.a"
 fi
 
-AC_ARG_WITH(x264inc,       --with-x264inc=dir     specify the directory of x264 header, V_INCLUDE_X264=$withval, V_INCLUDE_X264="")
-dnl x264 header needs pre-included headers
-dnl
-if test "$V_INCLUDE_X264" != "" ; then
-   if test ! -r $V_INCLUDE_X264/x264.h ; then
-	echo "Error! you need to have $V_INCLUDE_X264/x264.h around."
-	exit 1
-   fi
-   V_INCLUDE="$V_INCLUDE -I$V_INCLUDE_X264"
-elif test ! -r /usr/local/include/x264.h -a ! -r /usr/include/x264.h ; then
-        echo "Error! you need to have x264.h around."
-        exit 1
-else
-   echo "checking for x264.h...yes"
-fi
+AC_ARG_WITH(ffmpeginc,       --with-ffmpeginc=dir     specify the prefix directory of ffmpeg header, ffmpeginc=$withval, ffmpeginc="")
+AC_ARG_WITH(ffmpeglib,       --with-ffmpeglib=dir     specify the directory of ffmpeg library, ffmpeglib=$withval, ffmpeglib="")
 
-AC_ARG_WITH(x264lib,       --with-x264lib=dir     specify the directory of x264 library, V_LIB_X264=$withval, V_LIB_X264="")
-if test "$V_LIB_X264" != "" ; then
-   if test ! -r $V_LIB_X264/libx264.a ; then
-        echo "Error! you need to have $V_LIB_X264/libx264.a around"
-	exit 1
-   fi
-   V_LIB_X264="-L$V_LIB_X264 -lx264"
-else
-   AC_CHECK_LIB(x264, main, [], [
-        echo "Error! you need to have libx264 around."
-        exit -1
-   ])
-   V_LIB_X264="-lx264"
-fi
+if test "$ffmpegco" != "yes"; then
 
+	if test "$ffmpeginc" != "" ; then
+	   if test ! -r $ffmpeginc/ffmpeg/avcodec.h ; then
+	        echo "Error! you need to have $ffmpeginc/ffmpeg/avcodec.h around"
+	        exit 1
+	   elif test ! -r $ffmpeginc/ffmpeg/avutil.h ; then
+	        echo "Error! you need to have $ffmpeginc/ffmpeg/avutil.h around"
+	        exit 1
+	   elif test ! -r $ffmpeginc/ffmpeg/swscale.h ; then
+	        echo "Error! you need to have $ffmpeginc/ffmpeg/swscale.h around"
+	        exit 1
+	   fi
+	   echo "checking for FFmpeg headers...yes"
+	   V_INCLUDE="$V_INCLUDE -I$ffmpeginc"
+	
+	else
+
+	   AC_CHECK_HEADER(ffmpeg/avcodec.h, [], [
+        	echo "Error! you need to have avcodec.h around."
+	        exit -1
+	   ])
+	   AC_CHECK_HEADER(ffmpeg/avutil.h, [], [
+	        echo "Error! you need to have avutil.h around."
+	        exit -1
+	   ])
+	   AC_CHECK_HEADER(ffmpeg/swscale.h, [], [
+	        echo "Error! you need to have swscale.h around."
+	        exit -1
+	   ])
+	fi
+
+	if test "$ffmpeglib" != "" ; then
+	   if test ! -r $ffmpeglib/libavcodec.a ; then
+		echo "Error! you need to have $ffmpeglib/libavcodec.a around"
+	   elif test ! -r $ffmpeglib/libavutil.a ; then
+	        echo "Error! you need to have $ffmpeglib/libavutil.a around"
+	   elif test ! -r $ffmpeglib/libswscale.a ; then
+	        echo "Error! you need to have $ffmpeglib/libswscale.a around"
+	   fi
+	   V_LIB_FFMPEG="-L$ffmpeglib -lavcodec -lavutil -lswscale"
+	else
+	   AC_CHECK_LIB(avcodec, main, [], [
+	        echo "Error! you need to have libavcodec around."
+	        exit -1
+	   ])
+	   AC_CHECK_LIB(avutil, main, [], [
+	        echo "Error! you need to have libavutil around."
+	        exit -1
+	   ])
+	   AC_CHECK_LIB(swscale, main, [], [
+	        echo "Error! you need to have libswscale around."
+	        exit -1
+	   ])
+	   V_LIB_FFMPEG="-lavcodec -lavutil -lswscale"
+	fi
+fi 
+
+AC_ARG_WITH(x264inc,       --with-x264inc=dir     specify the directory of x264 header, x264inc=$withval, x264inc="")
+AC_ARG_WITH(x264lib,       --with-x264lib=dir     specify the directory of x264 library, x264lib=$withval, x264lib="")
+if test "x264co" != "yes" ; then
+	if test "$x264inc" != "" ; then
+	   if test ! -r $x264inc/x264.h ; then
+	        echo "Error! you need to have $x264inc/x264.h around."
+	        exit 1
+	   fi
+	   V_INCLUDE="$V_INCLUDE -I$x264inc"
+	elif test ! -r /usr/local/include/x264.h -a ! -r /usr/include/x264.h ; then
+	        echo "Error! you need to have x264.h around."
+	        exit 1
+	else
+	   echo "checking for x264.h...yes"
+	fi
+
+	if test "$x264lib" != "" ; then
+	   if test ! -r $x264lib/libx264.a ; then
+	        echo "Error! you need to have $x264lib/libx264.a around"
+		exit 1
+	   fi
+	   V_LIB_X264="-L$x264lib -lx264"
+	else
+	   AC_CHECK_LIB(x264, main, [], [
+	        echo "Error! you need to have libx264 around."
+	        exit -1
+	   ])
+	   V_LIB_X264="-lx264"
+	fi
+fi
 
 V_CPUDETECT=""
-AC_ARG_ENABLE(cpudetect, --enable-cpudetect     Enable or disable runtime cpu detection, cpudetect=no, cpudetect=yes)
+AC_ARG_ENABLE(cpudetect, --disable-cpudetect     Enable or disable runtime cpu detection, cpudetect="no", cpudetect="yes")
 if test "$arch" = "x86_32" -o "$arch" = "x86_64"; then
   if test "$cpudetect" = "yes"; then
+    echo "using CPU runtime detection..."
     V_OBJ="$V_OBJ linux/cpudetect.o"
     V_CPUDETECT="-DRUNTIME_CPUDETECT"
  fi
@@ -182,7 +205,7 @@ fi
 V_H261AS=""
 
 dnl h261 as (arbitrary size) 
-AC_ARG_ENABLE(h261as, --enable-h261as         Enable or disable the h261as codec, h261as=no, h261as=yes)
+AC_ARG_ENABLE(h261as, --disable-h261as         Enable or disable the h261as codec, h261as=no, h261as=yes)
 if test "$h261as" = "yes"; then
    V_OBJ="$V_OBJ codec/p64/p64as.o codec/decoder-h261as.o codec/encoder-h261as.o"
    V_H261AS="-DUSE_H261AS"
@@ -560,6 +583,7 @@ AC_SUBST(V_LIB_XIL)
 AC_SUBST(V_OBJ_XIL)
 AC_SUBST(V_OBJ)
 AC_SUBST(V_LIB)
+AC_SUBST(V_CODEC_LIB)
 
 V_DEFINE="$V_DEFINE $V_SHM $V_H261AS $V_DV $V_XV $V_CPUDETECT"
 
